
spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: YOUR_GOOGLE_CLIENT_ID
#            clientSecret: YOUR_GOOGLE_CLIENT_SECRET
#            scope:
#              - email
#              - profile
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
server :
  port : 8081





